PersonalSecurity/Areas/Admin/Controllers/AjaxCallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonalSecurity.Areas.Admin.Controllers
{
    public class AjaxCallController : Controller
    {
        //
        // GET: /Admin/AjaxCall/

        public ActionResult Index()
        {
            return View();
        }

        public class ReturnViewmodel
        {
            public int PrimaryKeyId { get; set; }
            public string ValueName { get; set; }
        }


        public ActionResult GetProvincesDistrictByProId(int id)
        {
            using (PersoanlSecurityEntities ent = new PersoanlSecurityEntities())
            {
                List<SelectListItem> ddlList = new List<SelectListItem>();

                var collection = ent.Database.SqlQuery<ReturnViewmodel>(@"select DistrictCode as PrimaryKeyId,NameNepali as ValueName From District where StateId='" + id + "' ").ToList();
                //var collection = ent.ProvincesDistrictSetup.Where(x => x.ProvincesId == id);

                foreach (var item in collection)
                {
                    ddlList.Add(new SelectListItem { Text = item.ValueName.ToString(), Value = item.PrimaryKeyId.ToString() });
                }
                var ddlSelectOptionList = ddlList;
                return Json(ddlSelectOptionList, JsonRequestBehavior.AllowGet);
            }
        }





        public ActionResult GetProvincesDistrictByProIdNew(int id)
        {
            using (PersoanlSecurityEntities ent = new PersoanlSecurityEntities())
            {
                List<SelectListItem> ddlList = new List<SelectListItem>();
                var collection = ent.Database.SqlQuery<ReturnViewmodel>(@"select DistrictCode as PrimaryKeyId,NameNepali as ValueName From District where StateId='" + id + "' ").ToList();
                //var collection = ent.ProvincesDistrictSetup.Where(x => x.ProvincesId == id);

                foreach (var item in collection)
                {
                    ddlList.Add(new SelectListItem { Text = item.ValueName, Value = item.PrimaryKeyId.ToString() });
                }
                var ddlSelectOptionList = ddlList;
                return Json(ddlSelectOptionList, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetProvincesVDCByProId(int id)
        {
            using (PersoanlSecurityEntities ent = new PersoanlSecurityEntities())
            {
                List<SelectListItem> ddlList = new List<SelectListItem>();

                var collection = ent.Database.SqlQuery<ReturnViewmodel>(@"select RuralMunicipalityId as PrimaryKeyId,NameNepali as ValueName  From RuralMunicipality where StateId='" + id + "' ").ToList();
                //var collection = ent.provincesVDCDetails.Where(x => x.ProvincesId == id);

                foreach (var item in collection)
                {
                    ddlList.Add(new SelectListItem { Text = item.ValueName, Value = item.PrimaryKeyId.ToString() });
                }
                var ddlSelectOptionList = ddlList;
                return Json(ddlSelectOptionList, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult GetProvincesVDCByDistrictId(int id, int StateId)
        {
            using (PersoanlSecurityEntities ent = new PersoanlSecurityEntities())
            {
                List<SelectListItem> ddlList = new List<SelectListItem>();
               // var collection = ent.provincesVDCDetails.Where(x => x.ProvincesDistrictId == id);
                var collection = ent.Database.SqlQuery<ReturnViewmodel>(@"select RuralMunicipalityId as PrimaryKeyId,NameNepali as ValueName From RuralMunicipality where DistrictId='" + id + "' and StateId='" + StateId + "'").ToList();
                foreach (var item in collection)
                {
                    ddlList.Add(new SelectListItem { Text = item.ValueName, Value = item.PrimaryKeyId.ToString() });
                }
                var ddlSelectOptionList = ddlList;
                return Json(ddlSelectOptionList, JsonRequestBehavior.AllowGet);
            }
        }




    }
}

PersonalSecurity/Controllers/AgencyRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PersonalSecurity.Areas.Admin.Models;
using PersonalSecurity.Areas.Admin.Providers;

namespace PersonalSecurity.Controllers
{
    public class AgencyRegistrationController : Controller
    {
        //
        // GET: /AgencyRegistration/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult AgencyRegister()
        {
            AgencySetupModel model = new AgencySetupModel();
            model.ProvincesId = 1;
            model.ProvincesDistrictId = 1;
            return View(model);
        }

        [HttpPost]
        public ActionResult AgencyRegister(AgencySetupModel model)
        {
            
            AgencySetupProviders pro = new AgencySetupProviders();
            model.Status = false;
            //check agency name or email already exist 
            if (CommonUtilities.IsUserNameAlreadyExist(model.EmailId))
            {
                ViewBag.EmailAlreadyExist = "Email already used in system.";
                return View(model);
            }

            if (pro.insertAgencySetup(model)=="Saved Successfully")
            {
                return RedirectToAction("Registered");
            }
            else
            {
                return View(model);
            }
            
        }

        public ActionResult Registered()
        {

            return View();
        }

    }
}

PersonalSecurity/Views/AgencyRegistration/AgencyRegister.cshtml
@model PersonalSecurity.Areas.Admin.Models.AgencySetupModel

@{
    ViewBag.Title = "AgencyRegister";
    Layout = "~/Views/Shared/_BlankLayout.cshtml";
}

<div class="right_col" role="main">
    <!-- top tiles -->
    <div class="row tile_count">
    </div>
    <!-- /top tiles -->

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                @if (ViewBag.EmailAlreadyExist != null)
                {
                    <span>@ViewBag.EmailAlreadyExist</span>
                }

                <div class="x_panel" style="">
                    <div class="x_title">
                        <h2>नयाँ निकायको विवरण</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="container">
                            <div class="col-md-12">
                                @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                                {
                                
                                    <div class="row">
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.AgencyName)
                                            @Html.TextBoxFor(m => m.AgencyName, new { @class = "form-control", @required = "required" })

                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.ProvincesId)
                                            @Html.DropDownListFor(m => m.ProvincesId, PersonalSecurity.CommonUtilities.GetprovincesNepal(), new { @class = "form-control", @required = "required", @onchange = "GetProvisionDistrictByProvisionId()" })

                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.ProvincesDistrictId)
                                            @Html.DropDownListFor(m => m.ProvincesDistrictId, PersonalSecurity.CommonUtilities.GetprovincesDistrictOfNepal(Model.ProvincesId), new { @class = "form-control", @required = "required", @onclick = "GetProvincesVDCDetailsByDistrictId()" })

                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.ProvincesVDCId)
                                            @Html.DropDownListFor(m => m.ProvincesVDCId, PersonalSecurity.CommonUtilities.GetVDCNPTitleOfProvincesByProvincesId(Model.ProvincesId, Model.ProvincesDistrictId), new { id = "ProvincesVDCID", @class = "form-control", @required = "required" })

                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.WardNumber)
                                            @Html.TextBoxFor(m => m.WardNumber, new { @class = "form-control", @required = "required" })

                                        </div>

                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.ContactNumber)
                                            @Html.TextBoxFor(m => m.ContactNumber, new { @class = "form-control", @required = "required" })

                                        </div>
                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.ShortDescription)
                                            @Html.TextBoxFor(m => m.ShortDescription, new { @class = "form-control", @required = "required" })

                                        </div>


                                        <div class="col-md-4 col-sm-12 col-xs-12 form-group">
                                            @Html.LabelFor(m => m.EmailId)
                                            @Html.TextBoxFor(m => m.EmailId, new { @class = "form-control", @required = "required" })
                                        </div>


                                    </div>
                                    
                                    <div class="ln_solid"></div>
                                    
                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            @Html.ActionLink("मुख्य पेज", "Login", "Account", null, new { @class = "btn btn-primary btn-sm" })
                                            @*<button class="btn btn-primary" type="button">Cancel</button>
                                            <button class="btn btn-primary" type="reset">Reset</button>*@
                                            <button type="submit" class="btn btn-primary btn-sm">दर्ता गर्नुहोस</button>
                                        </div>
                                    </div>

                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <br />
</div>
<script src="~/vendors/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    var k = jQuery.noConflict();
    function GetProvisionDistrictByProvisionId() {
        GetProvincesVDCDetails();
        var value = k('#ProvincesId option:selected').val();
        k.ajax({
            url: "@Url.Action("GetProvincesDistrictByProId", "AjaxCall", new { @area="Admin"})",
            type: 'POST',
            datatype: "json",
            data: { id: value },
            success: function (data) {
                var items = "";
                k.each(data, function (i, item) {
                    items += "<option value=\"" + item.Value + "\">" + item.Text + "</option>";
                });

                k("#ProvincesDistrictId").html(items);
            },
            failure: function () {
                alert('An error occurred.');
            }
        })
    }
</script>

<script type="text/javascript">
    var k = jQuery.noConflict();
    function GetProvincesVDCDetails() {
        var value = k('#ProvincesId option:selected').val();
        k.ajax({
            url: "@Url.Action("GetProvincesVDCByProId", "AjaxCall", new { @Area="Admin"})",
            type: 'POST',
            datatype: "json",
            data: { id: value },
            success: function (data) {
                var items = "";
                k.each(data, function (i, item) {
                    items += "<option value=\"" + item.Value + "\">" + item.Text + "</option>";
                });

                k("#ProvincesVDCID").html(items);
            },
            failure: function () {
                alert('An error occurred.');
            }
        })
    }
</script>

<script type="text/javascript">
    var k = jQuery.noConflict();
    function GetProvincesVDCDetailsByDistrictId() {

        var value = k('#ProvincesDistrictId option:selected').val();
        var StateId = k('#ProvincesId option:selected').val();
        k.ajax({
            url: "@Url.Action("GetProvincesVDCByDistrictId", "AjaxCall", new { @Area="Admin"})",
            type: 'POST',
            datatype: "json",
            data: { id: value, StateId: StateId },
            success: function (data) {
                var items = "";
                k.each(data, function (i, item) {
                    items += "<option value=\"" + item.Value + "\">" + item.Text + "</option>";
                });

                k("#ProvincesVDCID").html(items);
            },
            failure: function () {
                alert('An error occurred.');
            }
        })
    }
</script>

PersonalSecurity/Views/AgencyRegistration/Registered.cshtml
@{
    ViewBag.Title = "Registered";
    Layout = "~/Views/Shared/_BlankLayout.cshtml";
}



<div class="right_col" role="main">
    <!-- top tiles -->
    <div class="row tile_count">
    </div>
    <!-- /top tiles -->

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">


                <div class="x_panel" style="">
                    <div class="x_title">
                        <h2>तपाईँको विवरण पेश भयो । अन्य विवरणको लागि कृपया सम्बन्धित कार्यलयमा सम्पर्क गर्नुहोस वा आफ्नो ईमेल चेक गर्नुहोस ।</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                    </div>
                </div>
            </div>
        </div>


    </div>
    <br />
</div>